module.exports = {
    ASK_FAQ_DIALOG : "askFAQDialog",
    BOOKING_STATUS_DIALOG : "bookingStatusDialog",
    TICKET_CANCEL_DIALOG : "TICKET_CANCEL_DIALOG",
    CAROUSEL_BUTTON_DIALOG : "CAROUSEL_BUTTON_DIALOG",
    TICKET_BOOKING_DIALOG : 'ticketBookingDialog',
    TRAVEL_DESTINATION_ENQUERY_DIALOG : "TravelDestinationEnquery",
    WEATHER_STATUS_DIALOG : "WEATHER_STATUS_DIALOG",
    ALL_OPTIONS_BUTTON_DIALOG : "ALL_OPTIONS_BUTTON_DIALOG",
    MAIN_DIALOG : "mainDialog",
    CONVERSATION_DATA_PROPERTY : 'ConversationDataProperty',
    USER_PROFILE_PROPERTY : 'UserProfileProperty'

}